<?php
/**
 * Created by PhpStorm.
 * User: beren
 * Date: 06/08/2018
 * Time: 22:27
 */

namespace App\Security;


use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler;
use Symfony\Component\Security\Http\HttpUtils;

class AuthentificationSuccessHandler extends DefaultAuthenticationSuccessHandler
{
    /**
     * @var FlashBagInterface
     */
    private $flashBag;

    public function __construct(HttpUtils $httpUtils, array $options = array(), FlashBagInterface $flashBag)
    {
        parent::__construct($httpUtils, $options);

        $this->flashBag = $flashBag ;
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token)
    {
        $this->flashBag->add('success', 'You\'re login ! Welcome !');
        return parent::onAuthenticationSuccess($request, $token); // TODO: Change the autogenerated stub
    }
}